2019-11-07 12:10:03.401 parsl.dataflow.dflow:83 [DEBUG]  Starting DataFlowKernel with config
Config(
    app_cache=True, 
    checkpoint_files=None, 
    checkpoint_mode=None, 
    checkpoint_period=None, 
    data_management_max_threads=10, 
    executors=[ThreadPoolExecutor(
        label='threads', 
        managed=True, 
        max_threads=2, 
        storage_access=None, 
        thread_name_prefix='', 
        working_dir=None
    )], 
    initialize_logging=True, 
    lazy_errors=True, 
    max_idletime=120.0, 
    monitoring=None, 
    retries=0, 
    run_dir='runinfo', 
    strategy='simple', 
    usage_tracking=False
)
2019-11-07 12:10:03.402 parsl.dataflow.dflow:84 [INFO]  Parsl version: 0.9.0
2019-11-07 12:10:03.402 parsl.dataflow.usage_tracking.usage:126 [DEBUG]  Tracking status: False
2019-11-07 12:10:03.402 parsl.dataflow.usage_tracking.usage:127 [DEBUG]  Testing mode   : False
2019-11-07 12:10:03.402 parsl.dataflow.dflow:110 [INFO]  Run id is: e0913891-4f89-4700-b460-1674381712cc
2019-11-07 12:10:03.494 parsl.dataflow.memoization:52 [INFO]  App caching initialized
2019-11-07 12:10:03.495 parsl.dataflow.strategy:125 [DEBUG]  Scaling strategy: simple
2019-11-07 12:10:03.500 parsl.dataflow.dflow:484 [DEBUG]  Adding output dependencies
2019-11-07 12:10:03.500 parsl.dataflow.dflow:708 [INFO]  Task 0 submitted for App kmeans, waiting on tasks []
2019-11-07 12:10:03.500 parsl.dataflow.dflow:714 [DEBUG]  Task 0 set to pending state with AppFuture: <AppFuture super=<AppFuture at 0x7f3921995e10 state=pending>>
2019-11-07 12:10:03.500 parsl.dataflow.dflow:452 [INFO]  Task 0 launched on executor threads
2019-11-07 12:10:03.501 parsl.dataflow.dflow:484 [DEBUG]  Adding output dependencies
2019-11-07 12:10:03.501 parsl.dataflow.dflow:708 [INFO]  Task 1 submitted for App kmeans, waiting on tasks []
2019-11-07 12:10:03.501 parsl.dataflow.dflow:714 [DEBUG]  Task 1 set to pending state with AppFuture: <AppFuture super=<AppFuture at 0x7f3920ea1be0 state=pending>>
2019-11-07 12:10:03.503 parsl.dataflow.dflow:452 [INFO]  Task 1 launched on executor threads
2019-11-07 12:10:03.508 parsl.dataflow.dflow:484 [DEBUG]  Adding output dependencies
2019-11-07 12:10:03.508 parsl.dataflow.dflow:708 [INFO]  Task 2 submitted for App kmeans, waiting on tasks []
2019-11-07 12:10:03.509 parsl.dataflow.dflow:714 [DEBUG]  Task 2 set to pending state with AppFuture: <AppFuture super=<AppFuture at 0x7f3920eb1dd8 state=pending>>
2019-11-07 12:10:03.510 parsl.dataflow.dflow:452 [INFO]  Task 2 launched on executor threads
2019-11-07 12:10:03.514 parsl.dataflow.dflow:484 [DEBUG]  Adding output dependencies
2019-11-07 12:10:03.514 parsl.dataflow.dflow:708 [INFO]  Task 3 submitted for App kmeans, waiting on tasks []
2019-11-07 12:10:03.515 parsl.dataflow.dflow:714 [DEBUG]  Task 3 set to pending state with AppFuture: <AppFuture super=<AppFuture at 0x7f3920eb18d0 state=pending>>
2019-11-07 12:10:03.516 parsl.dataflow.dflow:452 [INFO]  Task 3 launched on executor threads
2019-11-07 12:10:03.517 parsl.dataflow.dflow:484 [DEBUG]  Adding output dependencies
2019-11-07 12:10:03.520 parsl.dataflow.dflow:708 [INFO]  Task 4 submitted for App kmeans, waiting on tasks []
2019-11-07 12:10:03.520 parsl.dataflow.dflow:714 [DEBUG]  Task 4 set to pending state with AppFuture: <AppFuture super=<AppFuture at 0x7f3920eb17b8 state=pending>>
2019-11-07 12:10:03.523 parsl.dataflow.dflow:452 [INFO]  Task 4 launched on executor threads
2019-11-07 12:10:03.528 parsl.dataflow.dflow:484 [DEBUG]  Adding output dependencies
2019-11-07 12:10:03.530 parsl.dataflow.dflow:708 [INFO]  Task 5 submitted for App kmeans, waiting on tasks []
2019-11-07 12:10:03.530 parsl.dataflow.dflow:714 [DEBUG]  Task 5 set to pending state with AppFuture: <AppFuture super=<AppFuture at 0x7f3920eb1588 state=pending>>
2019-11-07 12:10:03.532 parsl.dataflow.dflow:452 [INFO]  Task 5 launched on executor threads
2019-11-07 12:10:03.539 parsl.dataflow.dflow:864 [INFO]  DFK cleanup initiated
2019-11-07 12:10:03.539 parsl.dataflow.dflow:750 [INFO]  Summary of tasks in DFK:
2019-11-07 12:10:03.539 parsl.dataflow.dflow:781 [INFO]  Tasks in state States.launched: 0, 1, 2, 3, 4, 5
2019-11-07 12:10:03.539 parsl.dataflow.dflow:788 [INFO]  End of summary
2019-11-07 12:10:03.539 parsl.dataflow.dflow:888 [INFO]  Terminating flow_control and strategy threads
2019-11-07 12:10:03.542 parsl.executors.threads:96 [DEBUG]  Done with executor shutdown
2019-11-07 12:10:03.542 parsl.executors.threads:96 [DEBUG]  Done with executor shutdown
2019-11-07 12:10:03.544 parsl.dataflow.dflow:920 [INFO]  DFK cleanup complete
2019-11-07 12:10:03.942 parsl.dataflow.dflow:288 [INFO]  Task 0 completed
2019-11-07 12:10:04.109 parsl.dataflow.dflow:288 [INFO]  Task 2 completed
2019-11-07 12:10:04.274 parsl.dataflow.dflow:288 [INFO]  Task 3 completed
2019-11-07 12:10:04.483 parsl.dataflow.dflow:288 [INFO]  Task 4 completed
2019-11-07 12:10:04.698 parsl.dataflow.dflow:288 [INFO]  Task 5 completed
2019-11-07 12:10:04.841 parsl.app.errors:158 [DEBUG]  Reraising exception of type <class 'RuntimeError'>
2019-11-07 12:10:04.843 parsl.dataflow.dflow:257 [DEBUG]  Task 1 failed
2019-11-07 12:10:04.844 parsl.dataflow.dflow:279 [ERROR]  Task 1 failed after 0 retry attempts
Traceback (most recent call last):
  File "/home/kalpani/.local/lib/python3.5/site-packages/parsl/dataflow/dflow.py", line 254, in handle_exec_update
    res.reraise()
  File "/home/kalpani/.local/lib/python3.5/site-packages/parsl/app/errors.py", line 163, in reraise
    reraise(t, v, tb)
  File "/home/kalpani/.local/lib/python3.5/site-packages/six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "/home/kalpani/.local/lib/python3.5/site-packages/parsl/app/errors.py", line 172, in wrapper
    return func(*args, **kwargs)
  File "kmeans.py", line 31, in kmeans
    plt.scatter(X[:,0], X[:,1], c= kmeans.labels_, cmap='rainbow')
  File "/usr/lib/python3/dist-packages/matplotlib/pyplot.py", line 3241, in scatter
    ax = gca()
  File "/usr/lib/python3/dist-packages/matplotlib/pyplot.py", line 928, in gca
    return gcf().gca(**kwargs)
  File "/usr/lib/python3/dist-packages/matplotlib/pyplot.py", line 578, in gcf
    return figure()
  File "/usr/lib/python3/dist-packages/matplotlib/pyplot.py", line 527, in figure
    **kwargs)
  File "/usr/lib/python3/dist-packages/matplotlib/backends/backend_tkagg.py", line 84, in new_figure_manager
    return new_figure_manager_given_figure(num, figure)
  File "/usr/lib/python3/dist-packages/matplotlib/backends/backend_tkagg.py", line 101, in new_figure_manager_given_figure
    icon_img = Tk.PhotoImage(file=icon_fname)
  File "/usr/lib/python3.5/tkinter/__init__.py", line 3397, in __init__
    Image.__init__(self, 'photo', name, cnf, master, **kw)
  File "/usr/lib/python3.5/tkinter/__init__.py", line 3353, in __init__
    self.tk.call(('image', 'create', imgtype, name,) + options)
RuntimeError: main thread is not in main loop
2019-11-07 12:10:04.851 parsl.app.errors:158 [DEBUG]  Reraising exception of type <class 'RuntimeError'>
