2019-11-06 22:20:11.161 parsl.dataflow.dflow:83 [DEBUG]  Starting DataFlowKernel with config
Config(
    app_cache=True, 
    checkpoint_files=None, 
    checkpoint_mode=None, 
    checkpoint_period=None, 
    data_management_max_threads=10, 
    executors=[ThreadPoolExecutor(
        label='threads', 
        managed=True, 
        max_threads=2, 
        storage_access=None, 
        thread_name_prefix='', 
        working_dir=None
    )], 
    initialize_logging=True, 
    lazy_errors=True, 
    max_idletime=120.0, 
    monitoring=None, 
    retries=0, 
    run_dir='runinfo', 
    strategy='simple', 
    usage_tracking=False
)
2019-11-06 22:20:11.161 parsl.dataflow.dflow:84 [INFO]  Parsl version: 0.9.0
2019-11-06 22:20:11.161 parsl.dataflow.usage_tracking.usage:126 [DEBUG]  Tracking status: False
2019-11-06 22:20:11.161 parsl.dataflow.usage_tracking.usage:127 [DEBUG]  Testing mode   : False
2019-11-06 22:20:11.161 parsl.dataflow.dflow:110 [INFO]  Run id is: 2913d3cd-fcd1-40e6-8cf7-51ceab109b2f
2019-11-06 22:20:11.268 parsl.dataflow.memoization:52 [INFO]  App caching initialized
2019-11-06 22:20:11.268 parsl.dataflow.strategy:125 [DEBUG]  Scaling strategy: simple
2019-11-06 22:20:11.428 parsl.dataflow.dflow:484 [DEBUG]  Adding output dependencies
2019-11-06 22:20:11.428 parsl.dataflow.dflow:708 [INFO]  Task 0 submitted for App fun_df, waiting on tasks []
2019-11-06 22:20:11.428 parsl.dataflow.dflow:714 [DEBUG]  Task 0 set to pending state with AppFuture: <AppFuture super=<AppFuture at 0x7f61d10c55c0 state=pending>>
2019-11-06 22:20:11.428 parsl.dataflow.dflow:452 [INFO]  Task 0 launched on executor threads
2019-11-06 22:20:11.428 parsl.dataflow.dflow:288 [INFO]  Task 0 completed
2019-11-06 22:20:11.431 parsl.dataflow.dflow:484 [DEBUG]  Adding output dependencies
2019-11-06 22:20:11.431 parsl.dataflow.dflow:708 [INFO]  Task 1 submitted for App app_dropColumns, waiting on tasks []
2019-11-06 22:20:11.431 parsl.dataflow.dflow:714 [DEBUG]  Task 1 set to pending state with AppFuture: <AppFuture super=<AppFuture at 0x7f61b64c8048 state=pending>>
2019-11-06 22:20:11.431 parsl.dataflow.dflow:452 [INFO]  Task 1 launched on executor threads
2019-11-06 22:20:11.432 parsl.app.errors:158 [DEBUG]  Reraising exception of type <class 'AttributeError'>
2019-11-06 22:20:11.432 parsl.dataflow.dflow:257 [DEBUG]  Task 1 failed
2019-11-06 22:20:11.432 parsl.dataflow.dflow:279 [ERROR]  Task 1 failed after 0 retry attempts
Traceback (most recent call last):
  File "/home/kalpani/.local/lib/python3.5/site-packages/parsl/dataflow/dflow.py", line 254, in handle_exec_update
    res.reraise()
  File "/home/kalpani/.local/lib/python3.5/site-packages/parsl/app/errors.py", line 163, in reraise
    reraise(t, v, tb)
  File "/home/kalpani/.local/lib/python3.5/site-packages/six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "/home/kalpani/.local/lib/python3.5/site-packages/parsl/app/errors.py", line 172, in wrapper
    return func(*args, **kwargs)
  File "threaddf.py", line 17, in app_dropColumns
    dfUserDroppedCols = df.drop(inputs, axis=1)
AttributeError: 'list' object has no attribute 'drop'
2019-11-06 22:20:11.432 parsl.app.errors:158 [DEBUG]  Reraising exception of type <class 'AttributeError'>
2019-11-06 22:20:11.446 parsl.dataflow.dflow:864 [INFO]  DFK cleanup initiated
2019-11-06 22:20:11.446 parsl.dataflow.dflow:750 [INFO]  Summary of tasks in DFK:
2019-11-06 22:20:11.446 parsl.dataflow.dflow:781 [INFO]  Tasks in state States.done: 0
2019-11-06 22:20:11.446 parsl.dataflow.dflow:781 [INFO]  Tasks in state States.failed: 1
2019-11-06 22:20:11.446 parsl.dataflow.dflow:788 [INFO]  End of summary
2019-11-06 22:20:11.447 parsl.dataflow.dflow:888 [INFO]  Terminating flow_control and strategy threads
2019-11-06 22:20:11.447 parsl.executors.threads:96 [DEBUG]  Done with executor shutdown
2019-11-06 22:20:11.447 parsl.executors.threads:96 [DEBUG]  Done with executor shutdown
2019-11-06 22:20:11.447 parsl.dataflow.dflow:920 [INFO]  DFK cleanup complete
